"use client";

import React, { ReactNode } from "react";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import NavBar from "./../components/navBar";
import { Providers } from "@/GlobalRedux/provider";
import Notification from "@/components/Notifications";
import 'react-toastify/dist/ReactToastify.css'
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Education Platform",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}


const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  const pathname = usePathname();
  const isLoginPage = pathname === "/login" || pathname === "/signup" || pathname === "/new-password" || pathname === "/forget-password" || pathname === "/otp";

  return (
    <html lang="en">
      <head>
        <title>Edu AI-Admin</title>
        <meta name="description" content="Edu AI-Admin" />
        <link rel="icon" type="image/x-icon" href="/images/Login.png" />
      </head>
      <body>

        <Providers>
        {!isLoginPage && <NavBar /> }
          <Notification/>
          {children}
        </Providers>

      </body>
    </html>
  );
};

export default RootLayout;
